version: '2.7'

services:
  postgres:
    image: postgres-dbz:15.3
    build: .
    container_name: postgres
    env_file: ./.env 
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
    networks:
      yanto-net:
        ipv4_address: 192.168.12.19

networks:
  yanto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
    external: true
