version: '3.7'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    env_file: ./.env 
    ports:
      - "5432:5432"
    networks:
      - yanto-net
  
  rest:
    image: apache/iceberg-rest-fixture
    container_name: iceberg-rest
    ports:
      - 8181:8181
    env_file: ./.env
    networks:
      - yanto-net

  spark-master:
    image: spark:2.5.2
    build: .
    container_name: spark-master
    hostname: master
    env_file: ./.env
    volumes:
      - ./data:/home/playground
    networks:
      - yanto-net
    ports:
      - 7077:7077
      - 8089:8080
      - 4040:4040

  spark-worker1:
    image: spark:3.5.2
    build: .
    container_name: spark-worker1
    env_file: ./.env
    environment:
      - MODE=worker
    networks:
      - yanto-net
    ports:
      - 8081:8081
    depends_on:
      - master

  spark-worker2:
    image: spark:3.5.2
    build: .
    container_name: spark-worker2
    environment:
      - MODE=worker
    env_file: ./.env
    networks:
      - yanto-net
    ports:
      - 8082:8081
    depends_on:
      - master

  spark-notebook:
    image: spark:3.5.2
    build: .
    container_name: spark-notebook
    environment:
      - MODE=notebook
    env_file: ./.env
    ports:
      - 8989:8989
    volumes:
      - ./data:/home/playground
    networks:
      - yanto-net
    depends_on:
      - master


networks:
  yanto-net:
    driver: bridge
    external: true
