[package]
name = "clickhouse-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive", "string"] }
clickhouse = "0.13.1"
dotenv = "0.15.0"
tokio = { version = "1.43.0", features = ["full"] }
