services: '2.7'

services:
  debezium:
    image: quay.io/debezium/connect
    container_name: debezium
    environment:
      CONFIG_STORAGE_TOPIC: "my-connect-configs" 
      OFFSET_STORAGE_TOPIC: "my-connect-offsets"
      BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
    links:
      - kafka-server
      - zookeeper
    ports:
      - 8083:8083
    networks:
      - yanto-net

networks:
  yanto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
    external: true
