version: '3.7'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    depends_on:
      - postgres
    deploy:
      resources:
        limits: 
          cpus: '1'
          memory: 500M
    networks:
      analytic-net:
      yanto-net:
        ipv4_address: 192.168.12.16
  
  kafka:
    image: kafka:3.8.0
    build:
      context: .
    container_name: kafka-server
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      analytic-net:
      yanto-net:
        ipv4_address: 192.168.12.17
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M

networks:
  yanto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
    external: true

  analytic-net:
    driver: bridge
    external: true
