version: '3.1'

networks:
  yanto-net:
    driver: bridge
    external: true

services:
  sheet-connector:
    image: sheet-connector
    build: .
    container_name: sheet-connector
    networks:
      - yanto-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SHEET_ID: "15OLymPX48U-W4mFAuAoOH7DyS8i16sjH4GC31l_q1z4"
      TABLE_NAME: "test_table"
    depends_on:
      - kafka-server
